import type { Vacancy } from "./types";

export const vacanciesMock: Vacancy[] = [
	{
		id: "v1",
		title: "Frontend-разработчик (React)",
		company: "Ossetia Tech",
		city: "Цхинвал",
		salaryFrom: 120000,
		salaryTo: 220000,
		currency: "₽",
		experience: "1-3",
		schedule: "full",
		tags: ["React", "TypeScript", "Vite"],
		postedAt: "2026-01-10",
	},
	{
		id: "v2",
		title: "Оператор call-центра",
		company: "Сервис+",
		city: "Цхинвал",
		salaryFrom: 45000,
		salaryTo: 65000,
		currency: "₽",
		experience: "no",
		schedule: "full",
		tags: ["Коммуникация", "CRM"],
		postedAt: "2026-01-08",
	},
	{
		id: "v3",
		title: "Курьер",
		company: "Доставка 15",
		city: "Цхинвал",
		salaryFrom: 70000,
		salaryTo: 140000,
		currency: "₽",
		experience: "no",
		schedule: "part",
		tags: ["Подработка", "Гибкий график"],
		postedAt: "2026-01-06",
	},
	{
		id: "v4",
		title: "UI/UX дизайнер",
		company: "Studio North",
		city: "Цхинвал",
		salaryFrom: 90000,
		salaryTo: 160000,
		currency: "₽",
		experience: "1-3",
		schedule: "remote",
		tags: ["Figma", "UI Kit", "UX"],
		postedAt: "2026-01-05",
	},
	{
		id: "v5",
		title: "Бухгалтер",
		company: "Альфа-Баланс",
		city: "Цхинвал",
		salaryFrom: 60000,
		salaryTo: 95000,
		currency: "₽",
		experience: "3-6",
		schedule: "full",
		tags: ["1С", "Отчётность"],
		postedAt: "2026-01-02",
	},
	{
		id: "v6",
		title: "Junior QA Engineer",
		company: "Ossetia Tech",
		city: "Цхинвал",
		salaryFrom: 70000,
		salaryTo: 110000,
		currency: "₽",
		experience: "no",
		schedule: "remote",
		tags: ["Тестирование", "Чек-листы"],
		postedAt: "2026-01-01",
	},
];
